import * as day01 from './day01/report-repair';
import * as day02 from './day02/password-validation';
import * as day03 from './day03/trajectory';
import * as day04 from './day04/validate-passport';
import * as day05 from './day05/binary-boarding';
import * as day06 from './day06/custom-customs';
import * as day07 from './day07/handy-haversacks';
import * as day08 from './day08/handheld-halting';
import * as day09 from './day09/encoding-error';
import * as day10 from './day10/adapter-array';

console.time();
day01.execute();
day02.execute();
day03.execute();
day04.execute();
day05.execute();
day06.execute();
day07.execute();
day08.execute();
day09.execute();
day10.execute();
console.timeEnd();