import * as day1 from './day1/report-repair';
import * as day2 from './day2/password-validation';
import * as day3 from './day3/trajectory';
import * as day4 from './day4/validate-passport';
import * as day5 from './day5/binary-boarding';
import * as day6 from './day6/custom-customs';
import * as day7 from './day7/handy-haversacks';
import * as day8 from './day8/handheld-halting';
import * as day9 from './day9/encoding-error';
import * as day10 from './day10/adapter-array';

console.time();
day1.execute();
day2.execute();
day3.execute();
day4.execute();
day5.execute();
day6.execute();
day7.execute();
day8.execute();
day9.execute();
day10.execute();
console.timeEnd();